use_frameworks!
inhibit_all_warnings!

platform :ios, '10.0'

target 'ERNiftyFoundation_Example' do
 
 pod 'ERNiftyFoundation', :path => '../'

  target 'ERNiftyFoundation_Tests' do
   
   inherit! :search_paths

    
  end
end
