use_frameworks!

platform :ios, '10.3'

target 'ERNiftyFoundation_Example' do
 
 pod 'ERNiftyFoundation', :path => '../'

  target 'ERNiftyFoundation_Tests' do
   
   inherit! :search_paths

    
  end
end
